service: emojicode-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}
  httpApi:
    id: ${file(envvars.json):${self:provider.stage}.apiGatewayId}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /emojicode
          method: POST
      - httpApi:
          path: /test
          method: POST
    role: arn:aws:iam::261810331311:role/general-lambda-role
    timeout: 29
    memorySize: 128

    environment:
      EC2_PEM: ${file(emojicode_ec2.pem)}

    vpc:
      securityGroupIds:
        - sg-5587361e
      subnetIds:
        - subnet-fc04daa0
        - subnet-08117c42
        - subnet-7ab92375
        - subnet-db3ce5bc
        - subnet-c2578fec
        - subnet-5c59b662

    # Mount an EFS filesystem
    fileSystemConfig:
      # ARN of EFS Access Point
      arn: arn:aws:elasticfilesystem:us-east-1:261810331311:access-point/fsap-0148c692fa2921d97
      # Path under which EFS will be mounted and accessible in Lambda
      localMountPath: /mnt/efs

plugins:
  - serverless-offline
