service: emojicode-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    role: arn:aws:iam::261810331311:role/general-lambda-role
    timeout: 29
    memorySize: 128

    environment:
      EC2_PEM: ${file(emojicode_ec2.pem)}

    vpc:
      securityGroupIds:
        - sg-5587361e
      subnetIds:
        - subnet-fc04daa0
        - subnet-08117c42
        - subnet-7ab92375
        - subnet-db3ce5bc
        - subnet-c2578fec
        - subnet-5c59b662

plugins:
  - serverless-offline